server:
    port: 1212
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/figma
        username: postgres
        password: Urmat0204
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
app:
    jwt:
        secret: Urmat&12

error:
    include-stacktrace: always
